### ISSUE TITLE
enclosure_groups.create() Does not take valid data and returns JSON error

### ISSUE THREAD

**Issue by saketmarodia** [HewlettPackard/oneview-python#103]
I am facing the same issue while EG creation, The JSON is valid and Creates a EG if the REST endpoint.
uri2="https://"+IP+"/rest/enclosure-groups"
response2 = requests.post(uri2,verify=False,json=EG_data,headers=Headers)

But it gives an error when using the Python SDK.

This is the same issue as Issue #84

**Comment by yuvirani** [comment]
@saketmarodia, We have fixed the issue and the changes have been merged. Please check it once and let us know the results.

**Comment by Georgimi** [comment]
Well , i tried with the new version today and still facing the same issue as well.
JSON is valid but SDK shows ('Unrecognized JSON field.', {'errorCode': 'UNRECOGNIZED_JSON_FIELD', 'message': 'Unrecognized JSON field.', 'details': 'The field named type near line 1, column 11 is not a valid field in this JSON object.', 'messageParameters': [], 'recommendedActions': ['Check the valid fields for this JSON object and remove or correct the unrecognized field.'], 'errorSource': None, 'nestedErrors': [], 'data': {}})

column 11 points to 'enclosureTypeUri': '/rest/enclosure-types/SY12000' in the JSON as far as i can see.

Regards
Michael

**Comment by yuvirani** [comment]
@Georgimi, I'm sorry that still you are facing the issue. To see the changes in python module, we need to do the below steps:
$ git clone https://github.com/HewlettPackard/oneview-python.git
$ cd oneview-python
$ pip install hpeOneView

Please let us know if this helps.

**Comment by Georgimi** [comment]
did that. 
Collecting hpeOneView
  Downloading hpeOneView-5.5.0.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 4.6 MB/s
Collecting future>=0.15.2
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 20.1 MB/s
Using legacy 'setup.py install' for hpeOneView, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Installing collected packages: future, hpeOneView
    Running setup.py install for future ... done
    Running setup.py install for hpeOneView ... done
Successfully installed future-0.18.2 hpeOneView-5.5.0

Still not working for EGs. 

Regards
Michael

**Comment by yuvirani** [comment]
@Georgimi, EG creation is  working fine in python without any issue, but its causing the problem in Ansible and I could reproduce the error in ansible.  We are working on it, will update you once it is fixed.

**Comment by yuvirani** [comment]
@Georgimi,
We need to understand that this is python environment related issue where the latest code changes are not getting reflected. Hence we came up with the below mentioned solution after making further analysis.

Steps to fix:

- Switch to root user
- Unset <oneview-python-repo-path> from PYTHONPATH environment variable if added already
- pip uninstall hpeOneView
- pip install hpeOneView (ensure latest changes are reflected in below mentioned path - /usr/local/lib/pythonX/dist-packages)

Please do check the paths depending on the python version you use.
·       pip ---> python2.7 (/usr/local/lib/python2.7/dist-packages)
·       pip3 ---> python3.6 (/usr/local/lib/python3.6/dist-packages) 

I hope this helps to resolve the issue.
